name: 'Set Repository Variable'

author: kroese

description: 'Action to set repository variables'

branding:
  icon: arrow-right
  color: "gray-dark"

inputs:
  name:
    description: Name
    required: true

  value:
    description: Value
    required: true

  repository:
    description: Repository name
    default: false
    required: false

  owner:
    description: Owner of repository
    default: false
    required: false

  org:
    description: Flag for organization
    default: false
    required: false

  token:
    description: Repository access token
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
